version: '2.23.3'

services:
  opendoor-chat-backend:
    image: opendoor-chat-backend:latest
    ports:
      - "8080:8080"
  opendoor-chat-frontend:
    image: opendoor-chat-frontend:latest
    ports:
    - "3000:3000"
  # inbound-smtp-server:
  #   image: inboundsmtpserver:latest
  #   ports:
  #     - "25:25"
